# Generated by Django 5.1.1 on 2024-10-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inicio", "0002_persona"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Auto",
        ),
    ]
