# Generated by Django 5.1.1 on 2024-10-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inicio", "0003_delete_auto"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="dni",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
